version: '3.9'
name: dog-walking

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env
    command: 'npm run dev'
    volumes:
      - ./app:/app/app
      - ./public:/app/public
      - ./tsconfig.json:/app/tsconfig.json
      - ./next.config.ts:/app/next.config.ts

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '52000:${DB_PORT}'
    volumes:
      - dog-walking:/var/lib/mysql
      - ./data:/app/data

volumes:
  dog-walking:
    driver: local
